  <div id="wrapper">
    <div id="login_outer">
			<div id="login_center">
				<div id="clearheadercenter"></div>
				<div class="clear">&nbsp;</div>

				<div id="mymain1" title="login_center">					
					<form method="post" action="index.php" name="loginform" id="loginform">
						<p>

						</p>
						<p align="center">
						User Name: <input type="text" size="10" name="username" id="username" />
						</p>
						<p align="center">
						Password: &nbsp;&nbsp;<input type="password" size="10" name="password" id="password" />
						</p>
						<p align="right">
						<input type="submit" name="login" id="login" value="Login" />
						</p>
					</form>					
					<div class="clear">&nbsp;</div>
				</div>
				<div id="clearfootercenter"></div>
			</div>
      <div id="login_left">
        <div id="clearheaderleft"></div>
        <div id="container-left">
					<div title="left">
						<div class="clear">&nbsp;</div>
					</div>
        </div>
        <div id="clearfooterleft"></div>
      </div>
      <div class="clear">&nbsp;</div>
    </div>
    <div id="login_gfx_bg_middle">&nbsp;</div>
  </div>
